### ISSUE TITLE
Placeholders on globo.com

### ISSUE THREAD

**Issue by edivaniadc** [easylist/easylistportuguese#155]
### Issue:
Empty placeholders on **globo.com** - homepage (Desktop and Mobile/Tablet version)

### Possible Filters:
`globo.com##div[id^="banner_home1_"]`
`globo.com##div[id^="banner_home2_"]`
`globo.com##div[id^="banner_home3_"]`
`globo.com##div[id^="banner_home4_"]`
`globo.com##div[id^="banner_home5_"]`
`globo.com##div[id^="banner_home6_"]` (Mobile/Tablet only > banner above Cultura)
`globo.com##div[id^="banner_home7_"]` (Mobile/Tablet only > banner above Top Globo)
`globo.com###banner_vitrine_container` (Desktop only > banner below Top Globo)

Adding these rules it would cover e.g.:
desktop: `banner_home1_container`
mobile: `banner_home1_m_container`
tablet: `banner_home1_t_container`

In this case I believe: `globo.com###banner_home1_t_container` could be removed from ELPortuguese.

### Screenshot:
<img width="1262" alt="gb" src="https://user-images.githubusercontent.com/57706597/149567861-dcc43811-99a8-45ee-85c7-f70065ee3006.png">

**Comment by felippesantos46** [comment]
Done @edivaniadc 😄
