### ISSUE TITLE
Ads on tuasaude.com

### ISSUE THREAD

**Issue by edivaniadc** [easylist/easylistportuguese#158]
### Issue
**1 -** Empty placeholders (labelled as `PUBLICIDADE`) throughout page: https://www.tuasaude.com/sintomas-de-sinusite/

Suggestion: `tuasaude.com##.mrec-container`

<img width="847" alt="tsl" src="https://user-images.githubusercontent.com/57706597/150986355-2daebdb0-f7ef-4d99-93f8-ae7879a1ad40.png">

**2 -** Empty placeholder at the sidebar https://www.tuasaude.com/h3n2-sintomas/

Suggestion: `tuasaude.com##div[id^="divGptAd_"]`

<img width="1068" alt="tsn" src="https://user-images.githubusercontent.com/57706597/150986403-e129ec34-640f-49e0-a501-1c4594a6f03f.png">

**3 -** Existing rule in ELPortuguese: `tuasaude.com###footerWidgets` hides the cookie consent message > class: _pageCookieConsentContainer_

Suggestion: 
Delete `tuasaude.com###footerWidgets` since `tuasaude.com##div[id^="divGptAd_"]` can hide the ad/placeholder above the cookie consent message.

<img width="1360" alt="cc" src="https://user-images.githubusercontent.com/57706597/150988141-ef5df5b3-65f7-4d14-b1f8-fb2d0ac6ba4a.png">

**Comment by felippesantos46** [comment]
@edivaniadc Done, `tuasaude.com###footerWidgets` was already in the list.

**Comment by edivaniadc** [comment]
Hello @felippesantos46, thank you so much for looking into it!
Regarding the cookie consent message it will come up only if rule: `tuasaude.com###footerWidgets` is manually disabled, because it hides the whole bottom overlay, so a suggestion would be to delete it from EL Portuguese since `tuasaude.com##div[id^="divGptAd_"]` can hide the ad/placeholder above the cookie consent message^

**Comment by edivaniadc** [comment]
Hi there @felippesantos46, I'm just wondering if you have the chance to check my last comment case^ please. 
Thanks in advance.

**Comment by edivaniadc** [comment]
> @edivaniadc Done !! 😄

Thank you so so much!!!
