### ISSUE TITLE
Redirect popup ads at yayanimes.net

### ISSUE THREAD

**Issue by edivaniadc** [easylist/easylistportuguese#168]
Block redirect popup ads at https://yayanimes.net/itou-junji-collection-episodio-12/

### Suggestion 1
Block all popups with rule:`/about:blank.*/$popup,domain=yayanimes.net` 
<img width="1372" alt="yn5" src="https://user-images.githubusercontent.com/57706597/161239534-ed3956e9-99b7-49fb-996a-43f1af58e6c1.png">

### Suggestion 2: 
Block image popup `||yayanimes.net/yaylogobranco.png$popup` (it redirects to other websites) and also block ad servers: 
`||rpphgyjeljx.com^`
`||napsiguk.com^`

<img width="1085" alt="yn6" src="https://user-images.githubusercontent.com/57706597/161239458-bf16f0d8-d3b4-4f57-bf47-6b40d0ae0c4f.png">

<img width="1373" alt="yn4" src="https://user-images.githubusercontent.com/57706597/161239589-1fdaab8b-1626-4e6c-847c-3b08db2e14e7.png">

**Comment by felippesantos46** [comment]
@edivaniadc Thank you 😸
