### ISSUE TITLE
sapo.pt

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylistportuguese#17]
Some placeholders near the top. Example page: `https://www.sapo.pt`. I propose `##.ad-ctn`

![image](https://user-images.githubusercontent.com/22780683/111089432-2a51ef00-852c-11eb-8417-d963970301ba.png)

OS: Windows 10 20H2
Adblockers: uBlock Origin 1.34.1b2 + I Don't Care About Cookies 3.2.9
Browser: Chrome 89.0.4389.90 x64
Lists in use: ↓ 
![image](https://user-images.githubusercontent.com/22780683/111089408-0b535d00-852c-11eb-9a95-4dc2828e961b.png)

**Comment by isacurad** [comment]
As the site shows Anti-AdBlock messages (apparently not all the time to all users) I think it's better to not add any filter to avoid trouble with that.

![image](https://user-images.githubusercontent.com/53664309/111355418-be6fa380-865d-11eb-8868-e91a16c86b72.png)
