### ISSUE TITLE
Block adserver at https://topflix.fm 

### ISSUE THREAD

**Issue by edivaniadc** [easylist/easylistportuguese#170]
Block adserver at https://topflix.fm
Redirect link: https://oubvpkedplvdpkv.com/

Suggested filter: `||oubvpkedplvdpkv.com^`

VPN location: Portugal
view-source:https://topflix.fm/filmes/assistir-online-a-baba/

<img width="1200" alt="t2c" src="https://user-images.githubusercontent.com/57706597/162328463-39a77114-74a4-48f8-902b-66376004027e.png">

Most popups are blocked by rule: `topflix.fm#$#abort-current-inline-script String.fromCharCode XMLHttpRequest`
<img width="979" alt="t7j" src="https://user-images.githubusercontent.com/57706597/162328511-528bd739-c8bb-4496-a7c6-ddc428ceb5b6.png">

**Comment by felippesantos46** [comment]
Thank you, closed at: [3330465](https://github.com/easylist/easylistportuguese/commit/33304653557c04ce42164a64f26a185a4f7e2be5)
