### ISSUE TITLE
lista.mercadolivre.com.br

### ISSUE THREAD

**Issue by fastrespawn** [easylist/easylistportuguese#188]
```https://lista.mercadolivre.com.br/psu#D[A:psu]``` 
(It may need a few search queries before seeing the ad div)

#### What happens?

Mercadolivre.com.br has implemented a new ad div on search results

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/134432455/a5a474c1-0bd8-40c0-a9e8-8409e4bc3dec)

#### Your settings:

- OS/version: Windows 10
- Browser/version: Firefox 113
- Adblock extension/version: Ublock Origin, easylist

**Comment by Khrin** [comment]
https://github.com/easylist/easylistportuguese/commit/b43efed37eb4c1b640fda3548d8a01014a7a2f60
