### ISSUE TITLE
folhademaputo.co.mz

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylistportuguese#25]
Some ads (Only visible if the window is ≤~1100px). Example page: `http://www.folhademaputo.co.mz/`.

I propose:
```
||folhademaputo.co.mz/banners^
folhademaputo.co.mz##.bg-pattern-hatch
```

![image](https://user-images.githubusercontent.com/22780683/111091169-5c664f80-8532-11eb-863f-0e6e1e7384e2.png)

OS: Windows 10 20H2
Adblockers: uBlock Origin 1.34.1b2 + I Don't Care About Cookies 3.2.9
Browser: Chrome 89.0.4389.90 x64
Lists in use: ↓ 
![image](https://user-images.githubusercontent.com/22780683/111089551-b2d08f80-852c-11eb-9636-4f9695ce91e4.png)

**Comment by isacurad** [comment]
https://github.com/easylist/easylistportuguese/commit/7d1660e4c128d9b81d194e2d7089903f2aa6397b
