### ISSUE TITLE
dicionario.priberam.org

### ISSUE THREAD

**Issue by Pccode66** [easylist/easylistportuguese#41]
There are blank ad spaces, and they change depending on the zoom level of the webpage. I have made these filters for blocking them:

```
dicionario.priberam.org##.pb-pub-4
dicionario.priberam.org##.pb-pub-5.span10
dicionario.priberam.org###skyscraper
dicionario.priberam.org##.pb-pub-ipad-only.pb-pub-1.span10
dicionario.priberam.org##.pb-pub-2.container.pb-content
dicionario.priberam.org##.pb-hide-in-print.pb-pub-8.container.pb-content
dicionario.priberam.org##.span10.pb-pub-3
dicionario.priberam.org###ContentPlaceHolder1_mobileBanner
```

**Comment by jabonsolo** [comment]
@Pccode66 I pushed [071ea64](https://github.com/easylist/easylistportuguese/commit/071ea6442156180684fffe790a8ddd2f405735a0). Could you let me know if this fixes the problem for you.

**Comment by Pccode66** [comment]
The existing filter `dicionario.priberam.org##div[class*="pb-pub-"]` is messing up the formatting of the webpage, try removing it.

**Comment by jabonsolo** [comment]
I did a fix on the filters, could you try now.
[fa63c47](https://github.com/easylist/easylistportuguese/commit/fa63c47d2f5498d59b980e9e061827cd32c42945)

**Comment by Pccode66** [comment]
It works now.
