### ISSUE TITLE
mundoeducacao.uol.com.br

### ISSUE THREAD

**Issue by Pccode66** [easylist/easylistportuguese#42]
I have filed an issue for the Adguard filterlist at https://github.com/AdguardTeam/AdguardFilters/issues/84964, but for now, I think it would be best to add it to EasyList Portuguese too.
URL: `https://mundoeducacao.uol.com.br/matematica`
Issue: There are blank ad placeholders on the webpage
Suggested Filters: `mundoeducacao.uol.com.br##[style="height:250px; width:300px;"]` and `mundoeducacao.uol.com.br##div[style="display: flex; align-items: center; justify-content: center; margin-top: 20px;"]`. 
I don't know whether the second filter is specific enough to avoid false positives or not.

**Comment by jabonsolo** [comment]
Added these two filters and another one.
