### ISSUE TITLE
brasilescola.uol.com.br

### ISSUE THREAD

**Issue by Pccode66** [easylist/easylistportuguese#43]
(If you are using Ublock Filters, add the exception I mentioned at https://github.com/uBlockOrigin/uAssets/issues/9405)

The filter `uol.com.br##div[id^="banner"]` is incorrectly blocking content.
With `uol.com.br##div[id^="banner"]` and EasyList Portuguese:
![image](https://user-images.githubusercontent.com/49125134/121101821-f573d200-c7d2-11eb-933e-08c555cacd2e.png)
With `uol.com.br##div[id^="banner"]` and `brasilescola.uol.com.br#@#div[id^="banner"]` and EasyList Portuguese:
![image](https://user-images.githubusercontent.com/49125134/121102293-9ebac800-c7d3-11eb-8ecc-8c6a345eadf3.png)

A possible filter for fixing this is `brasilescola.uol.com.br#@#div[id^="banner"]`.

**Comment by Pccode66** [comment]
`uol.com.br##.banner` is also incorrectly blocking content on EasyList Portuguese.

**Comment by Pccode66** [comment]
Ublock Origin contributors have already changed `uol.com.br##.banner` to `uol.com.br#@#.banner`, maybe you should remove or add an exception to `uol.com.br##.banner` in EasyList Portuguese?

**Comment by mile-ne** [comment]
@Pccode66 thanks for your report!
